### ISSUE TITLE
libft test manquants

### ISSUE THREAD

**Issue by thomasLeMeur** [yyang42/moulitest#12]
Tout d'abord merci pour le Moulitest.
Ensuite, je pense qu'il faudrait rajouter des tests où les pointeurs, et pointeurs de pointeurs, passés en paramètre sont à NULL (variables et fonctions).

**Comment by yyang42** [comment]
Hello, mais pas de quoi.
Tu parles de quel projet/test?

**Comment by thomasLeMeur** [comment]
Je parle du projet libft, le tout premier.
Et je dis ça en général, pour la plupart des fonctions testées :
- NULL en 1er paramètre pour ft_strncat
- NULL en 1er paramètre, &(list = NULL) en 1er paramètre, NULL en 2e
  paramètre pour ft_lstdel
- ...
  Pour tester si le codeur a protégé ses fonctions des segfaults, des
  doubles frees, ...
  Si tu veux je peux t'envoyer mon propre projet de tests.

2015-10-22 18:42 GMT+02:00 yyang42 notifications@github.com:

**Comment by yyang42** [comment]
Les cas NULL ne sont pas testés volontairement pour des fonctions de lib, c'est un choix.
Exemple, si tu executes le strlen(NULL) de la libc, ça segfault.

**Comment by thomasLeMeur** [comment]
Ok, autant pour moi.
En tout cas encore une fois merci et sûrement à bientôt

**Comment by yyang42** [comment]
A bientot.

2015-10-23 9:09 GMT+02:00 thomasLeMeur notifications@github.com:

> Ok, autant pour moi.
> En tout cas encore une fois merci et sûrement à bientôt
>
