### ISSUE TITLE
[GNL] 30_bonus_multiple_fd: reads bloquant sur les pipes

### ISSUE THREAD

**Issue by flhorizon** [yyang42/moulitest#20]
Hello

Je pense que vous êtes déjà au courant; les write ends des pipes ne sont pas fermés avant d'appeler get_next_line()   (d'où read() bloquant et timeout).

Je vous fais une pull request ?

**Comment by yyang42** [comment]
Hello @flhorizon, je check ton PR https://github.com/yyang42/moulitest/pull/21 ce week-end ;) Merci.

**Comment by yyang42** [comment]
PR merged
