### ISSUE TITLE
Abort trap: 6 %% Error 2

### ISSUE THREAD

**Issue by Rubixor** [yyang42/moulitest#29]
Bonjour,

Le test ne teste pas mes fonctions après memset et j'aimerais savoir pourquoi.

[ -------STARTING ALL UNIT TESTS------- ]

> > > > 00_part1_ft_atoi.spec.c ----- [Ok !] ................................
> > > > 00_part1_ft_bzero.spec.c ---- [Ok !] ...
> > > > 00_part1_ft_isalnum.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_isalpha.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_isascii.spec.c -- [Ok !] ....................
> > > > 00_part1_ft_isdigit.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_isprint.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_memccpy.spec.c -- [Ok !] ..
> > > > 00_part1_ft_memchr.spec.c --- [Ok !] .
> > > > 00_part1_ft_memcmp.spec.c --- [Ok !] ......
> > > > 00_part1_ft_memcpy.spec.c --- [Ok !] .
> > > > 00_part1_ft_memmove.spec.c -- [Ok !] ..
> > > > 00_part1_ft_memset.spec.c --- [Ok !] ...
> > > > make[1]: **\* [exec_tests] Abort trap: 6
> > > > make: **\* [libft_bonus] Error 2

Merci.

**Comment by chacha-42** [comment]
@Rubixor as-tu trouvé d'où venait l'erreur ? j'ai un problème similaire :(

**Comment by Rubixor** [comment]
Non désolée :x
