### ISSUE TITLE
ft_lstnew test with NULL

### ISSUE THREAD

**Issue by jlagneau** [yyang42/moulitest#32]
[This test is a really bad idea](https://github.com/yyang42/moulitest/blob/a7b8fc0b236b1391357d373531b6b87960355f49/libft_tests/tests/02_bonus_ft_lstnew.spec.c#L12) and it does not respect your notice : 

`Notes: Errors should never pass silently! (That's why we don't handle NULL cases.)`

**Comment by yyang42** [comment]
Hum, exception pour ce cas ci, car la description de la fonction ft_lstnew précise:

>  Si le paramètre content est nul, le champs content est initialisé à NULL et le champs content_size est initialisé à 0 quelque soit la valeur du paramètre content_size.

![image](https://cloud.githubusercontent.com/assets/3263787/12032079/741dd4e0-ae14-11e5-8193-bca65f98e82b.png)

**Comment by jlagneau** [comment]
My bad, j'avais pas lu le sujet depuis un bail.
