### ISSUE TITLE
GNL Header location

### ISSUE THREAD

**Issue by mtassett** [yyang42/moulitest#36]
Pour le projet GNL, le header est sensé être situé dans ./libft/includes (cf enoncé), or la compilation cherche dans '.', './includes', './includes/builtin' et './libs/libtowel'.

<pre>gcc -g -I . -I ../testframework/v3//includes -I /nfs/zfs-student-4/users/mtassett/Documents/gnl -I /nfs/zfs-student-4/users/mtassett/Documents/gnl/includes -I /nfs/zfs-student-4/users/mtassett/Documents/gnl/includes/builtin -I /nfs/zfs-student-4/users/mtassett/Documents/gnl/libs/libtowel/includes -D__MOULITEST__ -DPROTOTYPES="MT_ADD_PROTO(01_test_simple); MT_ADD_PROTO(02_test_eof_with_close); MT_ADD_PROTO(03_test_medium_string); MT_ADD_PROTO(04_test_return_values); MT_ADD_PROTO(05_test_error_handling); MT_ADD_PROTO(06_test_line_of_08); MT_ADD_PROTO(07_test_two_lines_of_08); MT_ADD_PROTO(08_test_few_lines_of_08); MT_ADD_PROTO(09_test_line_of_16); MT_ADD_PROTO(10_test_two_lines_of_16); MT_ADD_PROTO(11_test_few_lines_of_16); MT_ADD_PROTO(12_test_line_of_4); MT_ADD_PROTO(13_test_two_lines_of_4); MT_ADD_PROTO(14_test_few_lines_of_4); MT_ADD_PROTO(15_test_line_without_nl); MT_ADD_PROTO(16_test_line_of_8_without_nl); MT_ADD_PROTO(17_test_line_of_16_without_nl); MT_ADD_PROTO(30_bonus_multiple_fd); MT_ADD_PROTO(40_hard_test_medium_string); MT_ADD_PROTO(41_hard_test_large_file); MT_ADD_PROTO(42_hard_test_one_big_fat_line); " -DADD_TESTS="MT_ADD_SUITE(mt, 01_test_simple, suite_01_test_simple); MT_ADD_SUITE(mt, 02_test_eof_with_close, suite_02_test_eof_with_close); MT_ADD_SUITE(mt, 03_test_medium_string, suite_03_test_medium_string); MT_ADD_SUITE(mt, 04_test_return_values, suite_04_test_return_values); MT_ADD_SUITE(mt, 05_test_error_handling, suite_05_test_error_handling); MT_ADD_SUITE(mt, 06_test_line_of_08, suite_06_test_line_of_08); MT_ADD_SUITE(mt, 07_test_two_lines_of_08, suite_07_test_two_lines_of_08); MT_ADD_SUITE(mt, 08_test_few_lines_of_08, suite_08_test_few_lines_of_08); MT_ADD_SUITE(mt, 09_test_line_of_16, suite_09_test_line_of_16); MT_ADD_SUITE(mt, 10_test_two_lines_of_16, suite_10_test_two_lines_of_16); MT_ADD_SUITE(mt, 11_test_few_lines_of_16, suite_11_test_few_lines_of_16); MT_ADD_SUITE(mt, 12_test_line_of_4, suite_12_test_line_of_4); MT_ADD_SUITE(mt, 13_test_two_lines_of_4, suite_13_test_two_lines_of_4); MT_ADD_SUITE(mt, 14_test_few_lines_of_4, suite_14_test_few_lines_of_4); MT_ADD_SUITE(mt, 15_test_line_without_nl, suite_15_test_line_without_nl); MT_ADD_SUITE(mt, 16_test_line_of_8_without_nl, suite_16_test_line_of_8_without_nl); MT_ADD_SUITE(mt, 17_test_line_of_16_without_nl, suite_17_test_line_of_16_without_nl); MT_ADD_SUITE(mt, 30_bonus_multiple_fd, suite_30_bonus_multiple_fd); MT_ADD_SUITE(mt, 40_hard_test_medium_string, suite_40_hard_test_medium_string); MT_ADD_SUITE(mt, 41_hard_test_large_file, suite_41_hard_test_large_file); MT_ADD_SUITE(mt, 42_hard_test_one_big_fat_line, suite_42_hard_test_one_big_fat_line); " -DRENDU_PATH="\"/nfs/zfs-student-4/users/mtassett/Documents/gnl\"" tests/01_test_simple.spec.c tests/02_test_eof_with_close.spec.c tests/03_test_medium_string.spec.c tests/04_test_return_values.spec.c tests/05_test_error_handling.spec.c tests/06_test_line_of_08.spec.c tests/07_test_two_lines_of_08.spec.c tests/08_test_few_lines_of_08.spec.c tests/09_test_line_of_16.spec.c tests/10_test_two_lines_of_16.spec.c tests/11_test_few_lines_of_16.spec.c tests/12_test_line_of_4.spec.c tests/13_test_two_lines_of_4.spec.c tests/14_test_few_lines_of_4.spec.c tests/15_test_line_without_nl.spec.c tests/16_test_line_of_8_without_nl.spec.c tests/17_test_line_of_16_without_nl.spec.c tests/30_bonus_multiple_fd.spec.c tests/40_hard_test_medium_string.spec.c tests/41_hard_test_large_file.spec.c tests/42_hard_test_one_big_fat_line.spec.c main.c utils.c /nfs/zfs-student-4/users/mtassett/Documents/gnl/get_next_line.c  -o get_next_line_tests -L../testframework/v3/ -lmt_framework -lft -L /nfs/zfs-student-4/users/mtassett/Documents/gnl/libft
In file included from tests/01_test_simple.spec.c:1:
In file included from ./project.h:10:
/nfs/zfs-student-4/users/mtassett/Documents/gnl/get_next_line.h:18:11: fatal error: 'libft.h' file not found
# include "libft.h"
[...]</pre>

**Comment by yyang42** [comment]
Oui, en effet, il y a quelques headers en trop mais la recherche dans '.' est normalement suffisant.
Le sujet dit:

> Vous ne devez rendre que deux fichiers : get_next_line.c et get_next_line.h

![image](https://cloud.githubusercontent.com/assets/3263787/12410897/a3a654ce-be79-11e5-88cf-634b35907da6.png)

**Comment by mtassett** [comment]
Un peu plus loin dans le sujet, 
![screen shot 2016-01-19 at 5 51 49 pm](https://cloud.githubusercontent.com/assets/10778615/12425506/6031ec6a-bed5-11e5-8244-c7f5c18c5820.png)

**Comment by juschaef** [comment]
Si mes souvenirs sont bon, on devait rendre le get_next_line.h à la racine.
Dans la libft, il ne devait y avoir que la libft (sources + dossiers includes pour le .h)
Et au vu des lignes de compilation du sujet, c'est bien ca, il est pas coherent de compiler le .h du get_next_line avec la lib pour inclure les sources seulement apres ...

**Comment by mtassett** [comment]
Justement, pour compiler les .o il faut le header de la libft pour pouvoir utiliser ses fonctions, header qui doit être localisé dans libft/includes. le get_next_line.h doit bien être a la racine pas de soucis avec ça.
Il me semble que le sujet a changé ces dernières semaines.

**Comment by WolfByttner** [comment]
I think La Moulinette uses "-I libft/includes" (does anyone have a trace to verify this?). If so, we should include the flag as otherwise people risk getting confused about what to put in the racine.

**Comment by mtassett** [comment]
Yes it does but it don't look like they care, try to convince them!

**Comment by yyang42** [comment]
Sorry for taking so much time. The PR from @marc3825 has been merged https://github.com/yyang42/moulitest/pull/37  Thanks
