### ISSUE TITLE
Test strcmp && strncmp

### ISSUE THREAD

**Issue by kkuette** [yyang42/moulitest#40]
Les tests strcmp && strncmp ne sont pas complet;

Il manque de verifier si s1 != '\0' || s2[i] != '\0';
A la moulinette mes deux fonctions ont fail a cause de cette verification, il faudrait ajouter les tests suivants : 
              -strcmp("aaa", "");
              -strncmp("aaa", "");
              -strcmp("", "aaa");
              -strncmp("", "aaa");

cordialement tdenion;

**Comment by yyang42** [comment]
Fixed by https://github.com/yyang42/moulitest/pull/41 thanks to @marc3825
