### ISSUE TITLE
[libft] corriger le strjoin / malloc +1

### ISSUE THREAD

**Issue by yyang42** [yyang42/moulitest#45]
agadiffe: https://forum.intrav2.42.fr/topics/193/messages 
> pense également si ta le tmps, a corriger le strjoin. 
> car même si on ne met pas le + 1 dans le malloc, ton test et tous les autres d'ailleurs, mettent ok .....

**Comment by achedeuzot** [comment]
The tests are still in use, even the 2013 need then to check their old failed project :P
