### ISSUE TITLE
printf("%")

### ISSUE THREAD

**Issue by frsechet** [yyang42/moulitest#72]
Salut,

printf("%") fait un truc bizarre. Quand dans un main a part je fais ft_printf("%") et printf("%"), j'obtiens exactement la meme chose (c'est-a-dire rien), y compris la valeur de retour (0 dans les deux cas).

Par contre, dans le moulitest, ce meme test me sort ceci qui me semble parfaitement aberrant (et a mon avis un probleme avec le buffer de printf):
TEST: test_modulo_without_valid_specifier
=====   printf_out  =====
ret: 0

====================

===== ft_printf_out =====
ret: 10
printf("")

====================

A regarder?
Merci!

**Comment by yyang42** [comment]
Salut, Merci pour le feedback.
Ça arrive uniquement pour le printf("%")? Le comportement est il identique à chaque fois?
Je vais checker ça.

**Comment by frsechet** [comment]
Ça le fait à chaque fois (mais essayé sur une seule machine, je verrai demain si je change de poste), et ça arrive aussi dans des circonstances similaires sur un autre test mais je ne me souviens plus précisément lequel, de mémoire un des bonus_01 avec * et précision ou taille de champ negative, qui fait un message  de debug du même genre alors que le même test séparément dans un main indépendant produit le bon résultat.


Merci !

F. 



Envoyé depuis mon iPhone

**Comment by frsechet** [comment]
Voila, j'ai retrouve, c'est cet autre test qui merde : printf("{%*d}", -5, 42)

TEST: wildcard_for_min_width_negative
=====   printf_out  =====
ret: 7
{42   }

=========================

===== ft_printf_out =====
ret: 7
{+42  }

=========================

Quand je le fais séparement, je n'ai absolument pas ce + qui apparait sur mon ft_printf.

**Comment by yyang42** [comment]
Je n'ai pas encore trouvé l'origine du problème.
Au cas où, peux-tu voir si ça ne vient pas de ton ft_prinft en mettant un code similaire vers la fin de ton programme. Comme ca, tu verras si tu retournes la bonne chose en relançant le moulitest.
```
fprintf(stderr, "retour: %s", retour_de_ton_ft_printf);
```

**Comment by frsechet** [comment]
Aucun de mes putchar/putstr et autres putxxx ne me sort ce contenu. Ce qui est sorti ne figure dans aucune des strings que je genere. De quel retour tu parles?
Je suis en e1r9p20 aujourd'hui si besoin de parler en direct quand tu arrives!

**Comment by frsechet** [comment]
Une piste de recherche eventuellement: pour ce test (printf("%")), qui ne doit rien retourner, tu dois faire une comparaison entre av[1] et av[2]. Or av[2] est vide, et du coup il prend le prochain truc sur le stack, qui se trouve etre un truc bizarre.

Pour l'autre test cependant (+42), je ne me l'explique clairement pas.

**Comment by yyang42** [comment]
Ok, je passe te voir dans l aprem, ca sera plus simple :)
