### ISSUE TITLE
[ft_printf]

### ISSUE THREAD

**Issue by Shirese** [yyang42/moulitest#74]
Bonjour, j'ai un pb a la compilation de ft_printf, en effet utilisant Yosemite, mon GCC est en fait un alias vers clang-600.0.56.
Les erreurs suivantes apparaissent :
includes/test.h:23:9: error: redefinition of typedef 't_test' is a C11 feature
      [-Werror,-Wtypedef-redefinition]
includes/suite.h:21:9: error: redefinition of typedef 't_suite' is a C11 feature
      [-Werror,-Wtypedef-redefinition]
Cela signifie que mon clang est outdater par le GCC des iMacs ?
Une idee de solution, mis a part installer GCC sur ma machine ?

**Comment by yyang42** [comment]
Ce changement devrait résoudre le problème: https://github.com/yyang42/moulitest/commit/14068337d80cb1b2f0e45c5fd591a3c7c402e5d5
