### ISSUE TITLE
Abort trap: 6

### ISSUE THREAD

**Issue by Gwagwa7** [yyang42/moulitest#8]
> > > > Tests for libft
> > > > Source: github.com/yyang42/moulitest
> > > > Legend: (.) Ok / (F) Fail / (S) Segfault / (B) Bus error / (T) Timeout / (A) Abort
> > > > 
> > > > Notes: Errors should never pass silently! (That's why we don't handle NULL cases.)
> > > > 
> > > > [ -------STARTING ALL UNIT TESTS------- ]
> > > > 00_part1_ft_atoi.spec.c ----- [Ok !] ................................
> > > > 00_part1_ft_bzero.spec.c ---- [Ok !] ...
> > > > 00_part1_ft_isalnum.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_isalpha.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_isascii.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_isdigit.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_isprint.spec.c -- [Ok !] ...................
> > > > 00_part1_ft_memccpy.spec.c -- [Ok !] ..
> > > > 00_part1_ft_memchr.spec.c --- [Ok !] .
> > > > 00_part1_ft_memcmp.spec.c --- [Ok !] ......
> > > > 00_part1_ft_memcpy.spec.c --- [Ok !] .
> > > > 00_part1_ft_memmove.spec.c -- [Ok !] ..
> > > > 00_part1_ft_memset.spec.c --- [Ok !] ...
> > > > 00_part1_ft_strcat.spec.c --- [????] make[1]: **\* [exec_tests] Abort trap: 6
> > > > make: **\* [libft_part1] Error 2

J'obtiens cette erreur, mais je ne sais pas si ca vient de moi ou pas :s

**Comment by gtdudu** [comment]
Same, looks weird.

Edit: buf est declare en dur ! (char[9] n est pas assignable) le resultat sera bon parce que la fonction ecrit a la suite en memoire quoi qu il arrive sans faire de check (fonction pourrie d ou le strncat) donc pour passer le test il faudait malloc le buf.. ou recuperer le resultat de ft_strcat dans un nouveau char\* a chaque fois.

**Comment by lpoujade** [comment]
EDIT : c'était une de mes fonctions ( strlcat ). Mais bizarrement avec le même code sur d'autres machines ça marchait correctement.

meme probleme ici, que ce soit pour la part1 ou la part2

```
make[1]: *** [exec_tests] Abort trap: 6
make: *** [libft_part2] Error 2
```

**Comment by Rubixor** [comment]
J'ai le même problème :
make[1]: *** [exec_tests] Abort trap: 6
make: *** [libft_bonus] Error 2
