### ISSUE TITLE
Utilisation de printf sans flags qui empeche la compilation sur linux

### ISSUE THREAD

**Issue by Atelier-Morales** [yyang42/moulitest#80]
Attention à l'utilisation de printf sans flags qui empêche toute compilation sur les systèmes Linux qui ne sont pas aussi permissifs que Mac, surtout avec -Werror. Exemple : 
mt/mt_exec.c: In function ‘mt_print_result’:
mt/mt_exec.c:40:2: error: format not a string literal and no format arguments [-Werror=format-security]
  printf(color);

**Comment by yyang42** [comment]
Hey Fernan, merci pour le feedback.

Je vois, il faut utiliser prinft("%s", str), plutot que printf(str).

Dis, c'est possible que tu listes ici toutes les occurrences de printf sans flags?
Je ferrais les modifs asap.

Si tu peux faire un pull request, c'est encore mieux, mais je ne sais pas si tu as le temps pour ça ;)

Merci en tout cas.
