### ISSUE TITLE
Affichage du -l dans ft_ls

### ISSUE THREAD

**Issue by hivian42** [yyang42/moulitest#81]
Salut yang,

Je rencontre un problème au niveau de la lecture du -l. Quand j'execute avec le moulitest, des espaces en plus apparaissent entre les différents noms, tailles ..., alors que quand j'execute moi-même, l'affichage est parfait. Et inversement, si je modifie la tailles des espaces pour convenir au moulitest, l'affichage devient faux pour moi. Sais-tu d'où ça vient ?

**Comment by hivian42** [comment]
Problème résolu. Une étourderie de ma part. Dsl pour le post inutile.

**Comment by yyang42** [comment]
pas de soucis :)
