### ISSUE TITLE
get_next_line ne compile pas

### ISSUE THREAD

**Issue by jgigault** [yyang42/moulitest#89]
Salut,

Avec un get_next_line qui nécessite la "libft" le makefile ne compile pas.
En effet il manque l'include de libft.a : "-L rendu_path/libft -lft"

J'ai modifié quelques lignes pour proposer une solution, voir ici : https://github.com/jgigault/moulitest/commit/7ac3a4f3103d2383a7bb542637e5f4a570b1ff29

(je ne sais pas encore utiliser les pull request !)

**Comment by yyang42** [comment]
c'est fait. dis moi si ça marche now ;)

**Comment by jgigault** [comment]
Ca fonctionne merci !
