### ISSUE TITLE
lib asm, tests manquants

### ISSUE THREAD

**Issue by Joon-99** [yyang42/moulitest#9]
Il me manque des tests lorsque je teste les fonctions de la lib asm, malgre le fait que j'ai fini la partie 1 et 2 integralement:

Pour un 'make part2' : 
[ -------STARTING ALL UNIT TESTS------- ]

> > > > 01_part1_ft_bzero.spec.c ---- [Ok !] ...
> > > > 01_part1_ft_isalnum.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_isalpha.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_isascii.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_isdigit.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_isprint.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_tolower.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_toupper.spec.c -- [Ok !] ................................
> > > > 02_part2_ft_memcpy.spec.c --- [Ok !] .
> > > > 02_part2_ft_memset.spec.c --- [Ok !] ...

Pour un 'make part1' : 
[ -------STARTING ALL UNIT TESTS------- ]

> > > > 01_part1_ft_bzero.spec.c ---- [Ok !] ...
> > > > 01_part1_ft_isalnum.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_isalpha.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_isascii.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_isdigit.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_isprint.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_tolower.spec.c -- [Ok !] ................................
> > > > 01_part1_ft_toupper.spec.c -- [Ok !] ................................
> > > > [ ----------END OF UNIT TESTS---------- ]

Je ne peux pas encore tester avec le make part3 car je n'ai pas terminé ft_cat.

**Comment by yyang42** [comment]
Tu veux dire qu'en lançant "make part2", il n'y a plus d'affichage après "02_part2_ft_memset.spec.c" ?
Si c'est ça, il se peut que le soucis vient du test suivant: ft_puts.
Ce teste capture le stdout temporairement et le restore a la fin du test.
S'il y a un soucis pendant l exécution du test, la restoration du stdout peut échouer et tu te retrouves sans aucune sortie ...
Donc, essaie d'exécuter les tests sans "02_part2_ft_puts.spec.c" pour voir. Tu peux renommer 02_part2_ft_puts.spec.c en 02_part2_ft_puts.spec.c.skip (extension autre que .spec.c) pour qu'il ne se lance pas.

**Comment by Joon-99** [comment]
J'ai teste en enlevant le test de puts comme tu l'as indique, et je valide correctement tous les autres tests, donc le probleme semble bien venir de mon puts. Je ne vois pas vraiment d'ou ca vient mais bon. Merci de ton retour en tout cas.

**Comment by Joon-99** [comment]
J'ai reussi a resoudre le probleme en changeant : 

```
mov rsi, 10
```

Par : 

```
push 10
mov rsi, rsp
[...]
pop rax
```

Je ne comprends pas pourquoi un simple mov rsi, 10 ne suffit pas, mais il doit y avoir des subtilites de l'assembleur que je ne maitrise pas encore.
