### ISSUE TITLE
[ft_printf]  erreur {%3c}

### ISSUE THREAD

**Issue by ale-batt** [yyang42/moulitest#98]
Bonjour, 
Premierement merci pour ce moulitest !

Sur le test de printf("{%3c}", 0);
(test 50, fonction min_width_c)
ton printf affiche "{     " et valeur de retour 5,
alors que quand je le fais, le caratère "}" s'affiche bien a la fin !
je sais pas trop d'ou viens cette erreur, mais je me permet au moins de la remonter !

Cordialement, 
encore merci pour tout !

**Comment by yyang42** [comment]
Salut, Oui, en effet, le moulitest utilise le printf d origine pour imprimer le result. Donc tout ce qui est apres le \0 est juste zappé.
Ce que tu peux faire pour bien voir la difference, c'est d utiliser un main simple et faire un "cat -e" pour voir tous les caractères qui ont été write().

Pas de quoi :)

**Comment by ale-batt** [comment]
Il faudrait supprimer les {} pour que les test sois correct, sur quasi tout les exos de %c le problème apparait,
je supprime a la main, je note les exo necessaire si tu veux

**Comment by yyang42** [comment]
J'imagine que tu dois déjà verifié ça, mais es-tu certain que ton output est identique à celui de printf? normalement, la comparaison effectuée par le test doit passer pour ces cas. En tout cas, c'est le cas pour mon printf et celui quelques autres personnes.
